### ISSUE TITLE
Yet another issue about how many sets of files to ship

### ISSUE THREAD

**Issue by conartist6** [iter-tools/iter-tools#173]
I'm sorry, I can't let go of this. One last time:

We should ship an `iter-tools-es` library which contains sources which are only transpiled down to the level of the most current ecmascript specification that is at least implemented in node. This code will be used in applications which transpile their dependencies to the desired level, or are able to rely on being run in a current node version. The main iter-tools library will be as it is now, though I'd say it wouldn't be out of line to remove the non-es5 files eventually.

I'll do the work on the build to make it happen.

**Comment by sithmel** [comment]
This is haunting us for a while.
Shall we propose different solutions here, before implementing one ?
I'll write mine as soon as I have time

**Comment by sithmel** [comment]
In the mean time let's enumerate all shortcomings of the current system. I'll start:

- we can't import es2015/es2018 packages (we can use rollup instead of plain babel for that)
- it is counter intuitive (and a performance concern) having a es5 version being the default
- I had problem in the past convincing webpack to prefer mjs files, with subsequent issues with tree shaking (this needs to be double checked)

Issues of having a es2018 version only:
- this is probably not working for users that naively add the dependency without checking the es2018 level required. Given async iterables syntax will throw an error, even on es2015 compatible browser
- explaining the users what needs to be included for the transpilation is complex. What if the user uses an older babel ? or ts ?

**Comment by conartist6** [comment]
Yep, those are all shortcomings for sure. I'm not sure what you mean when you say "can't import es2015/es2018 packages". I think you generally can, but if you do it from typescript will there will be no typedefs : (

If we bundle with rollup, we might be able to get rid of the mjs files. Then instead of a dependency graph traversal problem we'll just have a pure static analysis problem for the end user to get tree shaking. uglify-es should handle that fine. Rollup unfortunately will not because it still doesn't understand PURE annotations, but I've got all the specs collected for that, I just need to get my PR fixed (maybe you could help me with that @sithmel) in order to get that support for Rollup. I do think that bundling everything would mean that we should/would ship two bundles (not separate packages) - one sync and one async. This would be a big deal for people like me. I would love to use the library at my place of work, but our current infra is too old to tree shake (we're working on it) and I can't bring myself to include sooo much code that will get shipped but never used. In don't think many people at all are using async iteration on web.

Finally the es2015/es2018/es5. I too would dearly like to not have es5 as the default export. Firstly, I don't think we should change that before we finish this release. Let's plan to do the iter-tools 7 release we've been working on and then fast follow with iter-tools 8, which drops support for es5. We can either tell webbies who need to support IE11 that they should transpile their dependencies, or we can release a one-off `iter-tools-es5`. I'd prefer not to release the one-off package, but if we don't we risk someone doing it for us. Maybe that's not a bad thing either though.

**Comment by KSXGitHub** [comment]
I would also like to drop es5, it would gives us freedom to use newer ECMAScript features.

**Comment by sithmel** [comment]
> can't import es2015/es2018 packages

If they are not transpiled to es5

> maybe you could help me with that @sithmel

sure, what can I do ?

> our current infra is too old to tree shake

that's why we provide the way to import using:

```js
const map = require ('iter-tools/es2018/map)
```

This would go away with rollup though :sob: 

> I would also like to drop es5, it would gives us freedom to use newer ECMAScript features.

In my company we still have 10% of the traffic coming from IE11. This happens when users are corporate (in my case schools) that don't update their pc very often.

For this selfish reason I'd like to provide a way to use iter-tools on IE11. Either by offering a transpiled version or showing a simple enough way to transpile the code (that would be my preferred way, if possible).

> I don't think iter-tools-es5 is necessary. Consumer can just transpile main module if they so choose.

If we are able to give a way that works easily for everybody, I would be happy to do so. But I as open ".babelrc" I start shaking my head: what if the user is using a different version of babel ? how can you explain them to modify their existent configuration to support iter-tools ... etc. I am not sure we are there yet

>  I too would dearly like to not have es5 as a default

This can be done I think

> Let's plan to do the iter-tools 7 release we've been working on and then fast follow with iter-tools 8

It can be an option. Let's postpone this decision when we are closer to iter-tools 7 release

**Comment by sithmel** [comment]
Fun fact. Just tried latest Jest 24.0.0: it still requires to transpile the code down to ES2015 before running the tests

**Comment by conartist6** [comment]
I mean jest is meant to do the transpilation step itself, which works better since then it has sourcemaps and everything. We have a rather strange jest setup where we transpile ahead of time.

**Comment by conartist6** [comment]
I think now that jest has projects support I could actually fix that so that jest would run a lot faster (by caching transpiled code) and have sourcemaps as it is meant to.

**Comment by sithmel** [comment]
@conartist6 Still we are able to test the transpiled code, but not the original one. I really wish async generator were supported! It is ES2018 after all ...

**Comment by conartist6** [comment]
You ask how we can explain to a consumer how to modify their babel config to support iter-tools.

Well needing to transpile a library is not specific to us. If we were really thoughtful, we'd make a gist or a project or something which consisted solely of documentation on how to transpile a dependency when using various configurations/tools/versions. Then we could, say, open PRs against sindresaurus projects and others that expect to be transpiled which to link to that open source documentation, and people could add documentation for various versions/setups as they encountered them

**Comment by conartist6** [comment]
Actually though I think jest should work fine. It's in node, and it can run any code that node knows how to execute. They reason it would be breaking is that it will always run the code through a transpiler first. It needs to do this to convert imports/exports into something node can understand.

When we don't pre-transpile at all, that transpiler will choke if the appropriate sytnax isn't supported. We can fix that if we cause jest to own the transpilation itself, by just adding the `@babel/plugin-syntax-async-generators` plugin to the configuration jest uses to run the es2018 tests.

Now that I thought through that properly, I will fix it today.
