### ISSUE TITLE
Add GitHub Actions CI

### ISSUE THREAD

**Issue by KSXGitHub** [iter-tools/iter-tools#273]
I find GitHub Actions boot significantly faster than Travis CI, it would provide us shorter feedback loop.

**Comment by conartist6** [comment]
Do you have numbers? Can you test it on a fork or branch or something?

**Comment by conartist6** [comment]
I will say that I find Travis to be pretty satisfactory. I seem to recall it takes about 1 minutes to boot, and 2 minutes to report on a build, which has never been too slow for me. It would be nice to have it report individual passes to Github as checks -- it would then start reporting some key pieces of status earlier. Aside from any technical considerations I'm a bit resistant to the idea of tossing out an established, independent, and as far as I can tell high quality service provider just because Github/Microsoft made a version of their service.

**Comment by conartist6** [comment]
Looking into what they have though, I can see that there might be some portions of the actions setup that would be useful to us. Our CI setup is going to get more complicated too once we need to build copies of the website.

**Comment by KSXGitHub** [comment]
> Do you have numbers? Can you test it on a fork or branch or something?

No, just intuition. But it seems like a few seconds right after `git push`.

> I will say that I find Travis to be pretty satisfactory

Well, we lose nothing from adding another CI

> I seem to recall it takes about 1 minutes to boot

GitHub Actions takes seconds to boot. (I didn't take build/test time into account, but it should be equal to Travis)

> I'm a bit resistant to the idea of tossing out an ...

I'm not suggesting that we toss out Travis, just adding GitHub CI in addition to existing Travis.

**Comment by conartist6** [comment]
Cool, OK. Are you going to to do the setup? Do you have the perms you need to do it?

**Comment by KSXGitHub** [comment]
First, you need to sign this organization (iter-tools) up to use the feature: https://github.com/features/actions/signup

Then, when the "actions" tag appears (which you may have to wait for months), you may create `.github/workflows/*.yml` for each actions.

**Comment by conartist6** [comment]
@KSXGitHub Looks like we got in. I see the actions tab now.

**Comment by KSXGitHub** [comment]
Once this [test](https://github.com/KSXGitHub/iter-tools/commit/547ac28e463d1a83a4a180eb514a45539d67f158/checks) is completed, I'd make a pull request.

**Comment by conartist6** [comment]
I'm still looking into this, so you know. I have gotten it to the point where we could report the individual checks on the PR as they complete in a fast and efficient way, but unfortunately it will still not be possible to view the output from a check until certain other checks complete.

**Comment by KSXGitHub** [comment]
> but unfortunately it will still not be possible to view the output from a check until certain other checks complete.

We could run a bot that report by commenting after each check.

**Comment by conartist6** [comment]
Sorry, to clarify: the pass fail status of an individual script (e.g. test, lint) can be reported as a "check". The thing is, if you find a failing check and click it, the failing console output may not be viewable yet.

**Comment by KSXGitHub** [comment]
> if you find a failing check and click it, the failing console output may not be viewable yet.

This was not my experience.

**Comment by conartist6** [comment]
We're on actions now, but we still just have a single check. There's still room for improvement in terms of allowing feedback on which checks failed, but it's not a big deal right now as the checks run in order of their cost and a large amount of the verification happens locally.

Linting catches more problems than ever and is run in pre-commit.

`tsc` also runs in pre-commit and has probably pretty much full coverage at this point since it type checks all the tests (which have ~99% coverage these days).

Jest runs in about 12 seconds since it only runs es2018 code now (minimally transpiled). It's been a long time since I've seen an error in es5 that didn't show up in es2018 now too, but we now have an es5 only package and CI checks to makes sure that package works according to the test specifications.

So yeah, I'm pretty happy with how everything is working except the code generator, and that is going to get its overhaul very soon now.
