### ISSUE TITLE
Concerning ES Modules: `node --experimental-modules` cannot load `iter-tools/es2018/index.mjs` due to import URLs lacking .mjs extension

### ISSUE THREAD

**Issue by KSXGitHub** [iter-tools/iter-tools#292]
`iter-tools` provides `*.mjs` files alongside `*.js` files as an ES module alternative. However, Node.js cannot load it due to import URLs lacking extension, which is required for ES modules.

Take [this example repo](https://github.com/KSXGitHub/iter-tools-issue-concerning-node-esm.git):
* If you run `npm run import-iter-tools-and-print-it`, it will emit an error.
* However, if you run `npm run import-tsfun-and-print-it`, it will succeed. _(`@tsfun/*` are packages that I made which support both CommonJS modules and ES modules)_

I also doubt that bundlers (such as parcel, webpack) are going to prioritize loading `*.mjs` first.

## Proposal

Use [`@make-mjs/main`](https://github.com/ksxnodeapps/make-mjs) to convert `*.mjs` files that `import` URLs without extension to `*.mjs` files that `import` URLs with proper suffixes (either `.mjs`, `/index.mjs` or others depend on importing targets).

**Example Code:**

```typescript
import main, { EventType } from '@make-mjs/main'
import path from 'path'

// main() returns an async iterator
const events = main({
  dirname: 'src',
  getNewPath: filename => path.join('dist/es2018', path.basename(filename)),
  /* more options */
})

for await (const event of events) {
  if (event.type === EventType.BeforeWrite) {
    console.log('Making', event.file.path)
  }

  if (event.type === EventType.AfterWrite) {
    console.log('Made', event.file.path)
  }
}
```

## How does `@make-mjs/*` work?

It uses `@babel/parser` to convert a file into AST, then find import/export URLs within that AST and correct it, and then uses `@babel/generator` to create output code.

## Be aware

* I just completed that package yesterday, feature is lacking (enough for my use case).
* I did not have `iter-tools` in mind when I created `@make-mjs/*`. I only made it for my own packages (such as `@tsfun/*`). As such, it won't adapt to `iter-tools`'s need unless developers of `iter-tools` submit pull requests to it.
* I am lazy, and I am busy with other things, so while feature requests is welcomed, pull requests is more welcomed.
* Tests are barely enough: While I am confident that my package works when all tests passed, when they fail, I am not sure if I know where it went wrong. For this reason, pull requests that add tests are most welcomed.
* May not work properly on Windows: It is because the difference between URL separator (always be `/`) and filesystem path separator (`/` on POSIX and `\` on Windows), combined with the fact that I do not use Windows. If someone can ensure it works on Windows, I will gladly accept pull requests.

**Comment by conartist6** [comment]
In fact webpack [does](https://webpack.js.org/configuration/resolve/#resolveextensions) preference `mjs` files when they exist. I can't find as clear documentation on parcel.

To clarify you're talking specifically about allowing the library to run when used with the newest `--experimental-modules` spec, which replaces a slightly older one that we had supported already.

In terms of your `@make-js` package, I can't figure out how it's meant to be used. Is it supposed to be a codemod that you run once and which overwrites your existing sources? Is it supposed to be a build step?

Actually I can't figure out why it'd be useful at all, since the whole point of the new experimental modules spec is that you don't need your imports to end in `.mjs`. All we need to do is add `"type": "module"` ([docs here](https://nodejs.org/api/esm.html#esm_code_package_json_code_code_type_code_field)) to our `package.json` and then I'd think your sample app code will work fine.

**Comment by KSXGitHub** [comment]
> I can't find as clear documentation on parcel

I tested it once, out-of-the-box it only read commonjs files.

> In terms of your `@make-js` package, I can't figure out how it's meant to be used. Is it supposed to be a codemod that you run once and which overwrites your existing sources? Is it supposed to be a build step?

It is supposed to create new files (build step).

**Comment by conartist6** [comment]
And what does using it get us over just `"type": "module"`?

**Comment by KSXGitHub** [comment]
> And what does using it get us over just `"type": "module"`?

I still have to create package.json. There are cases, though rare, that I want to import iter-tools from afar (where package.json does not exist). It also seemed that parcel does not resolve to .mjs by default (I may be mistaken, I need to test further). Besides, why place limitations on user when there is a tool helps solve them.

**Comment by conartist6** [comment]
You misunderstand, I think. `"type": "module"` goes in the iter-tools package.json.

**Comment by conartist6** [comment]
"The nearest parent package.json is defined as the first package.json found when searching in the current folder, that folder’s parent, and so on up until the root of the volume is reached."

So I assume that this means if I'm parsing `src/index.mjs` and I encounter `import "./map"` I look for the nearest `package.json` which is the iter-tools package.json (even though I'm probably inside the `node_modules` folder of some other project). Because the package contains `"type": "module"` I now resolve the import to `src/map.mjs`.

**Comment by conartist6** [comment]
Presumably all the major bundling tools like webpack and parcel are going to support this resolution mechanism if they don't already.

**Comment by KSXGitHub** [comment]
> You misunderstand, I think. `"type": "module"` goes in the iter-tools package.json.

Yet `npm run import-iter-tools-and-print-it` fails?

**Comment by conartist6** [comment]
You tested with a version of `iter-tools` that has type: module set in package??

**Comment by KSXGitHub** [comment]
I see, which versions of `iter-tools` has `"type": "module"`?

**Comment by KSXGitHub** [comment]
Actually, I don't even find `"type": "module"` on [this very repo](https://github.com/iter-tools/iter-tools/blob/master/package.json).

**Comment by KSXGitHub** [comment]
Anyway, I have just manually add `"type": "module"` to `node_modules/iter-tools/package.json` and test what it can do:

- ✔️  I can import iter-tools by its name (`import 'iter-tools'`).
- ❌ I cannot import iter-tools specific es2018 versions, neither from `'iter-tools/es2018'` nor from `iter-tools/es2018/index.mjs`.
- ❌ I cannot import a specific file from iter-tools (`import 'iter-tools/es2018/map.mjs'`).

I also tried creating `iter-tools/es2018/package.json` with `{ "type": "module", "module": "index.mjs" }` but it doesn't work either.

Compare it to `@tsfun/all` which ticks ~all~ most boxes even without `"type": "module"` in any `package.json`.
- ✔️ I can import it by name: `import '@tsfun/all'`.
- ✔️ I can import a specific file: `import '@tsfun/option/unwrap.mjs'`.
- None of `@tsfun/*` uses subfolder so I am not sure about that.

**Comment by conartist6** [comment]
That's correct, iter-tools doesn't have that line in its package yet. And these are the test results I am interested in seeing. I'd be even more interested in know what the actual errors are! Anyway, I'm going to try it for myself.

**Comment by conartist6** [comment]
I'm getting completely different results than you. I used `npm pack` to generate a version of iter-tools from the current head after making some tweaks to `package.json`.

You're right that an extension is required to work in this mode, regardless of the type field in `package.json`. The old behavior of having an extension search order involving `.mjs` and `.js` is gone completely. That means that to work, we'll want to publish a version where all the files have the `.js` suffix, all the imports end with the `.js` suffix, and the `"type": "module"` is set in package, and `main` also needs to have the `.js` suffix instead of being extensionless.

This will destroy the ability to import the library as commonjs. In fact the docs contain a rather unsatisfying section which mentions that it is [not possible](https://nodejs.org/api/esm.html#esm_package_entry_points) to make a library which does double duty as a module library and a commonjs library. Fortunately the existing plan is to make an `iter-tools-es` package, and this only reinforces my desire to do that. The advantage of such a package is that it need to contain any of the transpiled-down sources, or the commonjs code. Eventually I anticipate that that will be the only way we ship iter-tools.

Anyway I don't see any need for `@make-mjs`. I still can't figure out why it isn't just a babel plugin package, and all we really need to do is to tweak a few lines in the sources and start publishing another package built slightly differently.

**Comment by KSXGitHub** [comment]
> Fortunately the existing plan is to make an iter-tools-es package, and this only reinforces my desire to do that

This is bad idea. My packages often support both commonjs and esm, which iter-tools am I supposed to use when I need to? Other users must double the effort too if they want to support all use cases.

>  still can't figure out why it isn't just a babel plugin package

Because I am not a babel user.

**Comment by KSXGitHub** [comment]
> That means that to work, we'll want to publish a version where all the files have the .js suffix, all the imports end with the .js suffix, and the "type": "module" is set in package, and main also needs to have the .js suffix instead of being extensionless.

Only es modules need .mjs extension. CommonJS can stay extensionless (when there is not `"type": "module"`). I mean, look at `@tsfun`.

**Comment by conartist6** [comment]
I'm definitely publishing a separate `iter-tools-es` package, mostly because it's going to be much, much smaller than any other package in terms of bundle size. The primary `iter-tools` package however will continue to support as many use cases as possible.

Also I don't see how you're going to be able to support commonjs and esm side by side if node doesn't. You're relying solely on extensionless imports (e.g. `import './foo'`) being resolved using a search path (e.g. look for `foo.mjs` then `foo.js`). This is precisely the mechanism which is not going to be part of node.

**Comment by KSXGitHub** [comment]
> Also I don't see how you're going to be able to support commonjs and esm side by side if node doesn't. You're relying solely on extensionless imports (e.g. import './foo') being resolved using a search path (e.g. look for foo.mjs then foo.js). This is precisely the mechanism which is not going to be part of node.

You are right and you are wrong. Let me repeat myself: ES modules that uses `import` requires `.mjs` extension; CommonJS modules that uses `require` DOES NOT requires `.js` extension. 

By using `@make-mjs`, I can support both CommonJS and ESM. I have tested it with `@tsfun`.

**Comment by conartist6** [comment]
Ah, right. OK. I'll do a similar setup iter-tools then, though I think I'll just write a babel plugin if I end up needing to, since I'm using babel already.

**Comment by KSXGitHub** [comment]
I'm glad you agreed. Few things:
1. Don't add `"type": "module"`: It breaks CommonJS modules.
2. If you can, choose/make production dependencies that supports .mjs, append `/index.mjs` (or other module entry) to import URLs that point to them (this is why `@make-mjs` is not so simple).
3. Every .mjs file needs its own TypeScript definition. Copy every `*.d.ts` to `*.mjs.d.ts`.
