### ISSUE TITLE
Implement `sum` function

### ISSUE THREAD

**Issue by chuckwondo** [iter-tools/iter-tools#342]
I'd like to suggest adding a `sum` function to sum all of the (numeric) values in an iterable, as part of your functions that reduce an iterable to a single value. (I find myself often writing a `sum` function with `reduce`, so it would be nice not to have to do that anymore.)

**Comment by conartist6** [comment]
I don't think I'm likely to add that to iter-tools.

The problem is that there's no need for the operation to be coupled to the reduce implementation. If you want to stop writing out `reduce((a, b) => a + b, 0)`, you have options. You could write exactly that snippet and export it from a shared location. That way currying has given you your `sum` function. I think even better would be to define the common mathematical operations somewhere: `add`, `mul`, `sub`, etc. Then you can write `reduce(0, add, iterable)`. Yes you have to do two imports for this instead of one, but I think that's easily worth in terms of the enhanced readability of the resulting code.

If you don't have a good spot for shared code, there are some existing packages on npm that would work, such as [arithmetic](https://www.npmjs.com/package/arithmetic).

**Comment by chuckwondo** [comment]
Thanks for the prompt reply. Sounds reasonable to me.
