### ISSUE TITLE
resettable iterator

### ISSUE THREAD

**Issue by Pyrolistical** [iter-tools/iter-tools#466]
I was surprised to be unable to find a resettable iterator with mark/reset, so I wrote one.

source: https://github.com/concept-not-found/patcom/blob/maybe/resettable-iterator.js
test: https://github.com/concept-not-found/patcom/blob/maybe/resettable-iterator.spec.js

would iter-tools be interested in taking this contribution? i'll relicense the code to MIT to remove any compatibility issues

**Comment by conartist6** [comment]
Interesting approach. My design is a bit different. In iter-tools, every single method is already "resettable". So long as calling `[Symbol.iterator]()` makes a new iterator instead of returning the same one, you can iterate as many times as you'd like completely independently of each other. But! Generator functions are also technically iterator factories, they just always return themselves. If you want a generator function that can run more than once, you have to write this:

```js
{
  *[Symbol.iterator]() {
    yield 1;
    yield 2;
    yield 3;
  }
}
```

I intend to create a utility function which will be called "regenerable" which takes a generator function and does exactly that to it.

**Comment by conartist6** [comment]
The implementation would be:
```js
function regenerable(generator) {
  return (...args) => ({
    [Symbol.iterator]() {
      return generator(...args);
    }
  });
}
```

**Comment by conartist6** [comment]
Would that satisfy your use case?

**Comment by conartist6** [comment]
On second thought, maybe I misread what you wrote. I actually think I already have this. Take a look at [forkerate](https://github.com/iter-tools/iter-tools/blob/trunk/API.md#forkerate).

**Comment by Pyrolistical** [comment]
ah yes, forkerate is exactly what my use case is. its just poorly named so i skipped over it. It has "rate" in the name so I assumed it it for async timing purposes

**Comment by conartist6** [comment]
Ah ok, great.

I wouldn't say it's poorly named, it's just an original invention to the best of my knowledge. I think what might help is providing a decision tree to help people figure out what method they should use. I seem to recall RX having something like that...
