### ISSUE TITLE
[Feature Request] min/max/minMax operators

### ISSUE THREAD

**Issue by hillin** [iter-tools/iter-tools#473]
For now I can use e.g.
```typescript
const minValue = Math.min(...execPipe( /* the pipeline */ ))
```

But it's a little bit cumbersome and does not feel like I've fully harnessed the power of pipeline. It would be great if we can simply write
```typescript
const minValue = execPipe( 
  /* the pipeline */ ,
  min
)
```

Same goes to `max` and (maybe) `minMax`.

By the way currently the following code does not work:
```typescript
const minValue = execPipe( 
  /* the pipeline */ ,
  arrayFrom,  // with or without arrayFrom
  Math.min
)
```

**Comment by conartist6** [comment]
```js
const minValue = execPipe( 
  iterable,
  /* the pipeline */ ,

  apply(Math.min),
  // OR
  reduce(Infinity, Math.min),
)
```

**Comment by conartist6** [comment]
`apply` does more what you suggest you want, being essentially equivalent to `iterable => fn(...iterable)`.

`reduce` is probably more costly to execute but it is also more idiomatic: whereas `apply` is forced to make a big array out of all the values before it can look for the minimum, `reduce` does the work incrementally thus avoiding having to ever allocate all the values into a big array.

It's a classic compute/memory tradeoff.

**Comment by conartist6** [comment]
Edited: use `reduce(Infinity, Math.min)` not `reduce(Math.min)` or else the code will blow up if you ever need to sum the empty iterable!

**Comment by hillin** [comment]
Thanks! `apply` is exactly what I wanted.

**Comment by hillin** [comment]
Oh I just realized I have to insert an `arrayFrom` before `apply`, so yeah it's still less idiomatic than I have expected. I'm aware of the `reduce` approach, but again as I think `min` and `max` are used very frequently, it would be handy if they can be more easily piped. So I'm reopening this issue here, please feel free to close it if you think it's out of scope.

**Comment by conartist6** [comment]
The reduce approach pipes fine doesn't it?

And what is the issue with `apply`? It should not require `arrayFrom`. The docs say it doesn't. The code looks like it doesn't to me. The tests should check that it works with an iterable that is not an array, but currently the tests for that method do not...

**Comment by conartist6** [comment]
I'm closing this again because as we've discussed there are already two idiomatic approaches. If either of them does not work as advertised, that is a separate issue. I hope you believe by now that you don't have to pile onto one thread just to make sure I'm still paying attention.

**Comment by hillin** [comment]
> The reduce approach pipes fine doesn't it?
> 
> And what is the issue with `apply`? It should not require `arrayFrom`. The docs say it doesn't. The code looks like it doesn't to me. The tests should check that it works with an iterable that is not an array, but currently the tests for that method do not...

On my first attempt the reduce approach did not work for me but I didn't think too much into it and switched to another approach. I tried again just now, it still didn't work - it looks a little bit weird to me but again I didn't think too much into it, just posting the facts here:

```typescript
const x = execPipe(
  [2, 7, 14],
  reduce(Infinity, Math.min)
);
```

this does not work, it always returns 0;

```typescript
const x = execPipe(
  [2, 7, 14],
  reduce(Infinity, (min, value) => Math.min(min, value))
);
```

this works, but makes the reduce approach less desirable.

**Comment by conartist6** [comment]
Ahhh yeah. Currently reduce calls `callback(accumulator, value, i)`. The first value for `i` is `0` and that's what you're seeing.

It's possible that the next major version of iter-tools will drop the pattern of passing `i` to callbacks completely. The iterator helpers proposal does not offer `i` callbacks, and I try to stick as closely as I can to the spirit of what the language is doing.

**Comment by conartist6** [comment]
Actually I believe even the iterator helpers proposal does use the three-arg callback pattern, it's just that the third argument is `undefined`. `Math.min(1, 2, undefined) === NaN` so in no version of this library is `reduce(Infinity, Math.min)` ever going to work. That's cause enough for me to add `min` and `max` methods I think!

**Comment by conartist6** [comment]
I'm tempted to say this will go in a package called (something like) `@iter-tools/math`. I also have plans for `@iter-tools/string` and a couple single-method packages like `@iter-tools/peekerate`. So far those package splits have proven difficult because to split anything out I need to be able to share the core parts of the library such as currying and the build. For now I could probably put the methods in the main library until such time as I am ready to split things out.

**Comment by alexd6631** [comment]
Hello @conartist6, 

First thank you for maintaining iter-tools, it is so far one of the best library for working with iterators in JS with functional operators. However, coming from the Kotlin world (which has an outstanding standard library for working with list/sequences), it seems to me there is still a few missing convenient operators.

I wanted to add weight to this issue that a max/min seems quite indispensible, but also maxBy/minBy operators.
Take the following code for instance : 

```
const persons = [
  { name: 'Foo', age: 35 },
  { name: 'Bar', age: 36 },
];

const oldest = execPipe(
  persons,
  maxBy((p) => p.age)
);
```

While technically feasible with a reduce `reduce((old, p) => old.age > p.age ? old : p)`, it is more verbose and would crash on an empty list. Whereas the min/max operators could return a T | undefined to handle the empty case (and it would be responsibility of the caller to handle this result).

If you are ok with including such operators (and don't have immediate plan to write it yourself), I may take the time to try make a PR.

Best regards

**Comment by conartist6** [comment]
Go ahead and make that PR! I think there should just be `min` and `max` methods, and they can take an optional accessor function parameter.

**Comment by conartist6** [comment]
What will `min` and `max` do when the input is empty?

**Comment by conartist6** [comment]
I think you'd need another argument for the initial/empty value. What if instead you created a new method called `reduceBy` or `mapReduce` which would take both a `mapper` and a `reducer`. Then your whole operation would look like this:


```js
const { max } = Math;

function __reduceBy(iterable, mapper, reducer, initial) {
  // ...
}

const oldest = __reduceBy(iterable, p => p.age, max, -Infinity);
```

EDIT: oh sorry you don't want the age, you want the actual oldest person. Let me think about this a moment.

**Comment by conartist6** [comment]
My point is that I'd rather solve a general problem so that the solution takes `Math.max` as an argument.

**Comment by conartist6** [comment]
How about a `pick` method? If the input iterable was non-empty it would return some element from its input. It would take a callback that would be a cross between a reducer callback and a find callback. It would be of the form `(picked, value) => boolean`, where a truthy return would indicate that `current` should become the new `picked`.  If the input iterable was empty it could return `undefined`, though a separate `pickOr` method could be provided to specify a particular when-empty return value.

All in all for your use case it would look like this:

```js
import { __pick } from 'iter-tools';

const people = [
  { name: 'Foo', age: 35 },
  { name: 'Bar', age: 36 },
];
const oldest = __pick(people, (picked, person) => person.age > picked.age);

assert(oldest.name === 'Bar');
```

**Comment by conartist6** [comment]
`pick` would be similar to `reduce`, but I think it would still be worth making it its own thing. There's two main reasons it would it's worth adding as an operation separate from `reduce`:

- It offers some slight sugar over `reduce` as you don't need to do `(acc, val) => /*...*/ ? acc : val`. Note that this isn't the biggest advantage because it would already be possible use a higher order helper to do that, e.g. `(cb) => (acc, val) => cb(acc, val) ? val : acc`
- It would always calls its callback n-1 times, where reduce calls it n times -- in other words it would always pick the first item from a list of one item.

**Comment by alexd6631** [comment]
I agree `pick` could be an interesting solution, and is definitely something different than reduce.
The downsides I see going this route (instead of implementing specialized min/max operators) are : 

  1.  Compared to a maxBy, if the mapper function is heavy to compute, it would be less efficient. Let's imagine we have some kind of solver, we have a set of solutions and want to pick the one that has the best score given a computeScore function (possibly heavy). `solutions.maxBy(computeScore)` vs `solutions.pick((s1, s2) => computeScore(s2) > computeScore(s1))`, the second one will recompute the best score at each step, so twice as much as computation.
  2. For new users looking for a min/max function, it will be easy to overlook the method and draw the conclusion that the library is missing this feature. Especially coming from Rust or Kotlin where these operators (and variants) are readily available.
  3. The term `pick` has already a semantic in other popular libraries such as lodash https://lodash.com/docs/4.17.15#pick, and is something different than what we are talking about, so it could lead to confusion.
  4. The boolean return value is ambiguous (should I return true / false for left / right ?)
 
However, there would be workarounds :

1. could be solved by providing a pickBy  `pickBy<T, K>(items: T, mapper: T => K, selector: (K, K) => boolean): T | undefined`. You could also map the item to their "score" in a tuple, at the previous step.
2. could be solved by adding entry in the doc to min/max and redirecting to the pick function, with examples
3. maybe, select/selectBy would be better here
4. not sure how we could solve that other than being extremely clear in the documentation.

**Comment by alexd6631** [comment]
FYI, I just opened a draft PR for a select operator (doc is missing), in order to get familiar with the codebase and the tooling : https://github.com/iter-tools/iter-tools/pull/486/files#diff-e293f79ac18400e524b6aea23c44a0f2c97724ebad341291dc40ece0c1f7583d

**Comment by alexd6631** [comment]
I just added a selectBy experimental implementation to my PR, and also implemented it in terms on peekerate (by inspiration on reduce), If you want to play with it. I will be off a few days, so I won't be able to answer until thursday. Hope it helps

**Comment by conartist6** [comment]
Wow, great. I'm going to move further discussion to your PR for now.
